# -*- coding: utf-8 -*-
"""exp 29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHWkm1gFJXvuj-beMFyHkd3EHxavfrBF
"""

from google import genai
import ast

print("================================")
print("PYTHON CODE GENERATION")
print("================================")

key=input("Enter your Gemini API key: ")
client=genai.Client(api_key=key)

problem=input("Enter the programming problem: ")

prompt=f"""
You are an expert Python programmer.

Generate a Python program for the following problem:

Problem:
{problem}

Requirements:
1. Use Python.
2. Use simple and readable code.
3. Accept required input from the user.
4. Produce the correct output.
5. Handle normal input properly.
6. Return only the Python program.
7. Do not include explanations or Markdown code fences.

Expected Output:
A complete executable Python program.
"""

try:
    response=client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt
    )

    code=response.text.strip()
    code=code.replace("```python","").replace("```","").strip()

    print("\nGenerated Python Code:")
    print(code)

    try:
        ast.parse(code)
        print("\nValidation Result: Valid Python syntax")
    except SyntaxError as e:
        print("\nValidation Result: Invalid Python syntax")
        print(e)

except Exception as e:
    print("\nError:")
    print(e)