# -*- coding: utf-8 -*-
"""exp 27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHWkm1gFJXvuj-beMFyHkd3EHxavfrBF
"""

from google import genai

print("================================")
print("TEXT GENERATION USING GEMINI API")
print("================================")

key=input("Enter your Gemini API key: ")
client=genai.Client(api_key=key)

while True:
    prompt=input("\nEnter your prompt (type exit to stop): ")

    if prompt.lower()=="exit":
        print("Program ended.")
        break

    try:
        response=client.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt
        )
        print("\nGenerated Output:")
        print(response.text)
    except Exception as e:
        print("\nError:")
        print(e)