# -*- coding: utf-8 -*-
"""exp 30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHWkm1gFJXvuj-beMFyHkd3EHxavfrBF
"""

from google import genai

print("================================")
print("SQL QUERY GENERATION")
print("================================")

key=input("Enter your Gemini API key: ")
client=genai.Client(api_key=key)

schema="""
Database: CollegeDB

Table: Students
Columns:
student_id INTEGER
name VARCHAR
department VARCHAR
marks INTEGER
"""

requirement=input("Enter your SQL requirement: ")

prompt=f"""
You are an expert SQL developer.

Database Schema:
{schema}

Task:
{requirement}

Instructions:
1. Generate the correct SQL query.
2. Use only the tables and columns given in the schema.
3. Do not invent columns.
4. Return only the SQL query.
5. Make the query syntactically clear and readable.

Expected Output:
A single SQL query.
"""

try:
    response=client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt
    )

    sql=response.text.strip()
    sql=sql.replace("```sql","").replace("```","").strip()

    print("\nGenerated SQL Query:")
    print(sql)

except Exception as e:
    print("\nError:")
    print(e)