# -*- coding: utf-8 -*-
"""exp 32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHWkm1gFJXvuj-beMFyHkd3EHxavfrBF
"""

from google import genai

print("================================")
print("PROMPT EVALUATION AND REFINEMENT")
print("================================")

key=input("Enter your Gemini API key: ")
client=genai.Client(api_key=key)

task=input("Enter the text generation task: ")

prompts=[
f"Write an answer for this task: {task}",
f"Give a clear, accurate and concise answer for this task: {task}",
f"""You are an expert writer.

Task:
{task}

Instructions:
- Give accurate information.
- Use simple and clear language.
- Include important points.
- Avoid unnecessary information.
- Organize the answer properly.

Output Format:
Title:
Answer:
"""
]

results=[]

for i,prompt in enumerate(prompts,1):
    try:
        response=client.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt
        )

        results.append(response.text.strip())

        print("\n========== PROMPT",i,"==========")
        print(response.text)

    except Exception as e:
        results.append("")
        print("\nError:",e)

evaluation_prompt=f"""
Evaluate the following three responses for the task.

Task:
{task}

Response 1:
{results[0]}

Response 2:
{results[1]}

Response 3:
{results[2]}

Evaluate each response using:
1. Relevance
2. Accuracy
3. Completeness
4. Clarity
5. Format adherence

Give a score out of 10 for each criterion.
Calculate the total score out of 50.
Select the best response.

Return the evaluation in a clear table.
"""

try:
    evaluation=client.models.generate_content(
        model="gemini-3.6-flash",
        contents=evaluation_prompt
    )

    print("\n========== EVALUATION ==========")
    print(evaluation.text)

    refine_prompt=f"""
Improve the following best response.

Task:
{task}

Response:
{results[2]}

Requirements:
- Improve clarity.
- Improve completeness.
- Maintain accuracy.
- Remove unnecessary information.
- Use a professional structure.

Return only the refined answer.
"""

    refined=client.models.generate_content(
        model="gemini-3.6-flash",
        contents=refine_prompt
    )

    print("\n========== REFINED RESPONSE ==========")
    print(refined.text)

except Exception as e:
    print("\nError:",e)