# -*- coding: utf-8 -*-
"""exp 31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHWkm1gFJXvuj-beMFyHkd3EHxavfrBF
"""

from google import genai

print("================================")
print("ZERO-SHOT ONE-SHOT FEW-SHOT")
print("================================")

key=input("Enter your Gemini API key: ")
client=genai.Client(api_key=key)

task=input("Enter the task: ")

zero=f"""
Perform the following task.

Task:
{task}

Give a clear and accurate answer.
"""

one=f"""
Perform the following task.

Example:
Task: Translate "Good morning" into French.
Answer: Bonjour.

Now perform:
{task}
"""

few=f"""
Perform the following task.

Examples:
Task: Translate "Good morning" into French.
Answer: Bonjour.

Task: Translate "Thank you" into French.
Answer: Merci.

Task: Translate "How are you?" into French.
Answer: Comment allez-vous?

Now perform:
{task}
"""

prompts=[
("Zero-Shot",zero),
("One-Shot",one),
("Few-Shot",few)
]

for name,prompt in prompts:
    try:
        response=client.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt
        )

        print("\n==========",name,"==========")
        print(response.text)

    except Exception as e:
        print("\nError:",e)